### ISSUE TITLE
Add !important to colors

### ISSUE THREAD

**Issue by DrewCPU** [lipis/bootstrap-social#9]
Can !important be added to all of the color and background-color attributes?  I place the social buttons into navbar dropdowns and the colors are getting overridden by the Bootstrap CSS, but adding !important seems to fix the issue.

**Comment by lipis** [comment]
Can you create a JSFiddle or something with the problem?! I really hate !important and I'm wondering why is that needed..

**Comment by topless** [comment]
You might be importing your custom css file before bootstrap. Make sure you have it last on the list.

**Comment by DrewCPU** [comment]
http://jsfiddle.net/DrewCPU/xm5Dr/ has everything loaded and you can see the issue.  I find that adding !important to the padding on .btn-social, the white color attributes, and the hover background colors fixed the problem for me.  I also moved the color attribute up to .btn-social instead of leaving it for every social network on my site (http://www.mywebwishlist.com).

**Comment by lipis** [comment]
In order to fix this problem few `!important` here and there will just make it more complicated because Bootstrap has many rules that are applied to the `<a>` of the `navbar`.

I would suggest you to change the links to `<button>` and handle them using JS.. by doing that you just need to adjust the width/height of the icon to match the Flatly theme because you're not using the .less files..

Check this example here.. and notice that I have very few changes:
http://jsfiddle.net/xm5Dr/6/

![screen shot 2014-01-21 at 18 50 51](https://f.cloud.github.com/assets/125676/1966180/ac34ca3c-82c4-11e3-8e0a-2348ba8bbbb8.png)

**Comment by lipis** [comment]
Just in case you want to avoid using JavaScript for the `<button>` because I changed from `<a>` you can wrap it inside a `<form>` and simulate the normal link like this:

```
<form action="/login/facebook">  
  <button class="btn btn-block btn-social btn-facebook">
    <i class="fa fa-facebook"></i>
    Sign in with Facebook
  </button>
</form>
```

The above code is more or less similar to the 

```
<button class="btn btn-block btn-social btn-facebook" href="/login/facebook?">
  <i class="fa fa-facebook"></i>
  Sign in with Facebook
</button>
```

**Comment by DrewCPU** [comment]
That'll work for me.  Thanks for all your work on these buttons.
